// Fallback config. Loaded after config.js — only sets CONFIG if the real file
// wasn't generated by the Actions workflow (e.g. local dev or missing secrets).
if (!window.CONFIG) {
  window.CONFIG = {
    github: "YOUR_GITHUB_USER", // your GitHub handle — also set via GH_USER secret
    repo: "daily-work",        // repo name — used by the refresh button
    gistId: "YOUR_GIST_ID",     // set via GIST_ID secret
    standupTime: "15:00",       // set via STANDUP_TIME secret
    standupTz: "Europe/Lisbon"  // set via STANDUP_TZ secret
  };
}